# Generated by Django 4.2.7 on 2023-12-01 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("manufacturer", models.CharField(max_length=100)),
                ("supplier_info", models.CharField(max_length=100)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("on_sale", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="base.drug"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="base.purchase",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="drug",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 0)), name="quantity_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="drug",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0)), name="price_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                check=models.Q(("purchase_price__gte", 0)), name="p_price_gte_0"
            ),
        ),
    ]
